Create python http equivalent of settingsManager.ts
refstudio/refstudio pull request #396
Opened 2023-08-22 22:53 UTC by gjreda

fixes #364
_____

I think this generic API for settings should be all we need, but let me know otherwise @cguedes @danvk

2023-08-23 07:04 UTC, cguedes requested changes

2023-08-23 07:04 UTC, cguedes commented on python/sidecar/http.py
> +@settings_api.post("/")
This should be PUT instead of POST as this will update settings instead of creating settings.

2023-08-23 07:04 UTC, cguedes commented on python/sidecar/typing.py
> +
We know the structure of the settings. Can't we have a strongly typed definition?

2023-08-23 12:48 UTC, gjreda commented on python/sidecar/settings.py
> +    filepath = Path(WEB_STORAGE_URL / "settings.json")
Yep, good catch

2023-08-24 07:57 UTC, cguedes approved these changes

2023-08-24 07:58 UTC, merged